name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  formatter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Formatter
        run: deno fmt --check
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Formatter
        run: deno lint
